### ISSUE TITLE
kind of a wrong path?

### ISSUE THREAD

**Issue by UKONNsoft** [mysticatea/eslint-custom-rule-tutorial#1]
great work, especially for beginners!

in package.json
regarding to custom rule path, "eslint/rule/*js" is to be "rule/*js", isn't it ?

**Comment by mysticatea** [comment]
Thank you for this issue!

It's my intention.
I guessed that names of code blocks in my article confused you, so I fixed those: http://qiita.com/mysticatea/items/cc3f648e11368799e66c/revisions/1
